name: Boorusphere
description: A new Flutter project.
homepage: https://github.com/nullxception/boorusphere
repository: https://github.com/nullxception/boorusphere.git

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  cached_network_image: ^3.0.0-nullsafety
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  fimber: ^0.6.1
  flutter_cache_manager: ^3.0.0-nullsafety.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_speed_dial: ^4.3.0
  freezed_annotation: ^0.14.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_generator: ^1.1.0
  hooks_riverpod: ^1.0.0-dev.11
  http: ^0.13.1
  json_serializable: ^5.0.2
  material_floating_search_bar: ^0.3.4
  mime: ^1.0.0
  package_info: ^2.0.0
  photo_view: ^0.12.0
  scroll_to_index: ^2.0.0
  shimmer: ^2.0.0
  settings_ui: ^1.0.0-nullsafety.2
  url_launcher: ^6.0.3
  xml2json: ^5.0.0
  yaml: ^3.1.0
  double_back_to_close: ^2.0.0
  video_player: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  effective_dart: ^1.3.0
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.1+2
  icapps_license:
    git:
      url: git://github.com/icapps/flutter-icapps-license.git
      ref: master

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/icon-base.png
  image_path_android: assets/icons/icon-circle.png
  adaptive_icon_foreground: assets/icons/logo.png
  adaptive_icon_background: "#2e2e2e"

icapps_license:
  nullsafety: true
  licenses:
    cached_network_image: https://raw.githubusercontent.com/Baseflow/flutter_cached_network_image/develop/cached_network_image/LICENSE
    cupertino_icons: https://raw.githubusercontent.com/flutter/packages/master/third_party/packages/cupertino_icons/LICENSE
    flutter_cache_manager: https://raw.githubusercontent.com/Baseflow/flutter_cache_manager/develop/LICENSE.md
    freezed: https://raw.githubusercontent.com/rrousselGit/freezed/master/packages/freezed/LICENSE
    freezed_annotation: https://raw.githubusercontent.com/rrousselGit/freezed/master/packages/freezed_annotation/LICENSE
  extra_licenses:
    icapps_license:
      name: icapps_license
      version: master
      url: https://github.com/icapps/flutter-icapps-license
      license: https://raw.githubusercontent.com/icapps/flutter-icapps-license/master/LICENSE
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/servers.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
